// This file is generated by scripts/generate-gallery-manifest.mjs.
// Do not edit it manually. Add or remove images in public/gallery and run npm run gallery:generate.

export const galleryItems = [
  {
    "id": 1,
    "image": "/gallery/gallery-01.jpeg",
    "alt": "Mujeres emprendedoras compartiendo",
    "kind": "story",
    "height": 432
  },
  {
    "id": 2,
    "image": "/gallery/gallery-02.jpeg",
    "alt": "Joyeria artesanal",
    "kind": "photo",
    "height": 490
  },
  {
    "id": 3,
    "image": "/gallery/gallery-03.jpeg",
    "alt": "Feria de emprendimientos",
    "kind": "video",
    "height": 697
  },
  {
    "id": 4,
    "image": "/gallery/gallery-04.jpeg",
    "alt": "Proceso de tejido artesanal",
    "kind": "photo",
    "height": 314
  },
  {
    "id": 5,
    "image": "/gallery/gallery-05.jpeg",
    "alt": "Arreglo floral artesanal",
    "kind": "video",
    "height": 697
  },
  {
    "id": 6,
    "image": "/gallery/gallery-06.jpeg",
    "alt": "Preparacion de alimentos",
    "kind": "photo",
    "height": 314
  },
  {
    "id": 7,
    "image": "/gallery/gallery-07.jpeg",
    "alt": "Taller creativo",
    "kind": "story",
    "height": 432
  },
  {
    "id": 8,
    "image": "/gallery/gallery-08.jpeg",
    "alt": "Gastronomia artesanal",
    "kind": "photo",
    "height": 490
  },
  {
    "id": 9,
    "image": "/gallery/gallery-09.jpeg",
    "alt": "Textiles de colores",
    "kind": "photo",
    "height": 490
  },
  {
    "id": 10,
    "image": "/gallery/gallery-10.jpeg",
    "alt": "Maquina de coser",
    "kind": "photo",
    "height": 314
  },
  {
    "id": 11,
    "image": "/gallery/gallery-11.jpeg",
    "alt": "Coleccion de moda",
    "kind": "story",
    "height": 697
  },
  {
    "id": 12,
    "image": "/gallery/gallery-12.jpeg",
    "alt": "Proceso de ceramica",
    "kind": "video",
    "height": 432
  },
  {
    "id": 13,
    "image": "/gallery/gallery-13.webp",
    "alt": "Atardecer sobre los Montes de Maria",
    "kind": "territory",
    "height": 432
  },
  {
    "id": 14,
    "image": "/gallery/gallery-14.jpg",
    "alt": "Iglesia rodeada de montanas y vegetacion",
    "kind": "territory",
    "height": 490
  },
  {
    "id": 15,
    "image": "/gallery/gallery-15.webp",
    "alt": "Puesta de sol sobre montanas y flores",
    "kind": "territory",
    "height": 697
  },
  {
    "id": 16,
    "image": "/gallery/gallery-16.jpg",
    "alt": "Mirador natural con flores y montanas verdes",
    "kind": "territory",
    "height": 314
  },
  {
    "id": 17,
    "image": "/gallery/gallery-17.jpeg",
    "alt": "Vista panoramica de un pueblo entre montanas",
    "kind": "territory",
    "height": 697
  },
  {
    "id": 18,
    "image": "/gallery/gallery-18.jpeg",
    "alt": "gallery 18",
    "kind": "photo",
    "height": 314
  },
  {
    "id": 19,
    "image": "/gallery/gallery-19.jpeg",
    "alt": "gallery 19",
    "kind": "photo",
    "height": 432
  },
  {
    "id": 20,
    "image": "/gallery/gallery-20.jpeg",
    "alt": "gallery 20",
    "kind": "photo",
    "height": 490
  },
  {
    "id": 21,
    "image": "/gallery/gallery-21.jpeg",
    "alt": "gallery 21",
    "kind": "photo",
    "height": 490
  },
  {
    "id": 22,
    "image": "/gallery/gallery-22.jpeg",
    "alt": "gallery 22",
    "kind": "photo",
    "height": 314
  },
  {
    "id": 23,
    "image": "/gallery/gallery-23.jpeg",
    "alt": "gallery 23",
    "kind": "photo",
    "height": 697
  },
  {
    "id": 24,
    "image": "/gallery/gallery-24.jpeg",
    "alt": "gallery 24",
    "kind": "photo",
    "height": 432
  },
  {
    "id": 25,
    "image": "/gallery/gallery-25.jpeg",
    "alt": "gallery 25",
    "kind": "photo",
    "height": 432
  },
  {
    "id": 26,
    "image": "/gallery/gallery-26.jpeg",
    "alt": "gallery 26",
    "kind": "photo",
    "height": 490
  },
  {
    "id": 27,
    "image": "/gallery/gallery-27.jpeg",
    "alt": "gallery 27",
    "kind": "photo",
    "height": 697
  },
  {
    "id": 28,
    "image": "/gallery/gallery-28.jpeg",
    "alt": "gallery 28",
    "kind": "photo",
    "height": 314
  },
  {
    "id": 29,
    "image": "/gallery/gallery-29.jpeg",
    "alt": "gallery 29",
    "kind": "photo",
    "height": 697
  },
  {
    "id": 30,
    "image": "/gallery/gallery-30.jpeg",
    "alt": "gallery 30",
    "kind": "photo",
    "height": 314
  },
  {
    "id": 31,
    "image": "/gallery/gallery-31.jpeg",
    "alt": "gallery 31",
    "kind": "photo",
    "height": 432
  },
  {
    "id": 32,
    "image": "/gallery/gallery-32.jpeg",
    "alt": "gallery 32",
    "kind": "photo",
    "height": 490
  },
  {
    "id": 33,
    "image": "/gallery/gallery-33.jpeg",
    "alt": "gallery 33",
    "kind": "photo",
    "height": 490
  },
  {
    "id": 34,
    "image": "/gallery/gallery-34.jpeg",
    "alt": "gallery 34",
    "kind": "photo",
    "height": 314
  },
  {
    "id": 35,
    "image": "/gallery/gallery-35.jpeg",
    "alt": "gallery 35",
    "kind": "photo",
    "height": 697
  },
  {
    "id": 36,
    "image": "/gallery/gallery-36.jpeg",
    "alt": "gallery 36",
    "kind": "photo",
    "height": 432
  },
  {
    "id": 37,
    "image": "/gallery/gallery-37.jpeg",
    "alt": "gallery 37",
    "kind": "photo",
    "height": 432
  },
  {
    "id": 38,
    "image": "/gallery/gallery-38.jpeg",
    "alt": "gallery 38",
    "kind": "photo",
    "height": 490
  },
  {
    "id": 39,
    "image": "/gallery/gallery-39.jpeg",
    "alt": "gallery 39",
    "kind": "photo",
    "height": 697
  },
  {
    "id": 40,
    "image": "/gallery/gallery-40.jpeg",
    "alt": "gallery 40",
    "kind": "photo",
    "height": 314
  },
  {
    "id": 41,
    "image": "/gallery/gallery-41.jpeg",
    "alt": "gallery 41",
    "kind": "photo",
    "height": 697
  }
] as const;
